version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-app
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
    networks:
      - my-network

  node-app:
    build: ./node-app
    container_name: node-app
    entrypoint: ["dockerize", "-wait", "tcp://database:3306", "-timeout", "20s", "node", "index.js"]
    environment:
      MYSQL_HOST: database
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
      PORT: 3000
    depends_on:
      - database
    networks:
      - my-network

  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: database
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - my-network

networks:
  my-network:
    driver: bridge